apiVersion: v1
kind: Template
metadata:
  name: pv-template
objects:
- apiVersion: v1
  kind: PersistentVolume
  labels:
    app: ${APP}-${RELTAG}
  metadata:
    annotations:
      pv.kubernetes.io/bound-by-controller: "yes"
    name: pv-logs-${APP}-${STAGE}-${RELTAG}
  spec:
    accessModes:
    - ReadWriteMany
    capacity:
      storage: 5Gi
    nfs:
      path: /export/logs/app1
      readOnly: false
      server: 10.10.10.10
    persistentVolumeReclaimPolicy: Retain
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: pvc-logs
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 5Gi
    volumeName: pv-logs-${APP}-${STAGE}-${RELTAG}
parameters:
- description: Application name, e.g. from Jira
  name: APP
- description: Release tag
  name: RELTAG
- description: Stage
  name: STAGE

